### ISSUE TITLE
Question about adding episode as watched

### ISSUE THREAD

**Issue by edison23** [adameste/anidbcli#13]
Sorry if were searching wrong but I haven't found any mention about this. My question:

When I add some series (ie. multiple episodes) to my list as unwatched but stored on my HDD and so on, then watch an episode and want to update my list in a way that that one episode will be recorded as watched, `anidbcli api -a anime-ep01.mkv` successfully generates the ed2k link but then throws a warning informing me the episode is already in my list and exits. Is it possible to update an episode which is already in my list with the `anidbcli` tool?

Just for the record:
`$ anidbcli --version`
`anidbcli, version 1.53`

Thanks a lot for your help and for the effort with the development! :)

**Comment by adameste** [comment]
Not implemented as of yet, didn't think of it. Will add a parameter to modify the state of episode instead of adding it in case it fails.

**Comment by adameste** [comment]
And implemented. If file is already in mylist, it will be marked as watched in version 1.60.

**Comment by edison23** [comment]
@adameste : thanks, i confirm it works as expected. 

I have only one question remaining, reading my original post here retrospectively, I have not been very clear on what I'm actually seeking. Is it possible to add episodes to my list just as unwatched stuff (ideally with `state` and `storage` fields filled) so I can just track what I have on my drives? I can do that rather easily via the native ed2k dump, the original goal of this was, aside from what has been achieved here already, ability to also add stuff not marking them as watched right away.

Again, thanks a lot for the prompt update of your app and generally for your time.

**Comment by adameste** [comment]
Good idea, added in version 1.63. Use -U option alongside -a (-aU) to add/mark files as unwatched. Someone already implemented --state [storage] option, check quickstart guide for options, it is merged in the PyPi version already.
