### ISSUE TITLE
Encoding in setup.py file

### ISSUE THREAD

**Issue by Jonybat** [adameste/anidbcli#4]
Hi

When installing from source it throws the following error:

  File "setup.py", line 12
SyntaxError: Non-ASCII character '\xc5' in file setup.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I'm using UTF-8 encoding.

According to docs, adding `# coding=latin-1` fixes it.

**Comment by adameste** [comment]
Merged

**Comment by adameste** [comment]
And i double checked, the encoding of the file is definitely utf-8. Since I am Czech the latin encoding messed up my name in PyPi repository.
