### ISSUE TITLE
Question/Feature Request

### ISSUE THREAD

**Issue by avluis** [adameste/anidbcli#7]
Is this program able to create target directories with parameters from hashed files?

For example, given a directory where new files are downloaded; I would like to move and rename files to:

\\AnimeShare\AnimeName [sometag-animeId]\EpisodeNo.VersionIfGreaterThanV1 -  [ShortGroupName] (LowerCaseCRC).extension

**Comment by adameste** [comment]
Yes, should work exactly as that. The program should generate all directories in the path (if it has the access rights) and move/copy/link the file to the newly created directory.

**Comment by avluis** [comment]
Thank you!
