### ISSUE TITLE
Just rename without generating ed2k links?

### ISSUE THREAD

**Issue by msdos** [adameste/anidbcli#8]
I'm not interested in generating ed2k links, but really interested in the rename feature. Problem is that everytime I rename a folder with a lot of files, it keeps creating the hashes taking a long time (specially in a low resource NAS).

Am I missing something or to rename it indeed needs to create the ed2k links? Are they used in the API for searching? If they are needed to the rename function to the files being properly renamed you can close this issue (although it would be nice to add this information to README).

BTW, thanks for this package!

**Comment by adameste** [comment]
Github still not sending e-mail about issues.

The ed2k link needs to be generated. The anidb edpisode/anime/etc info is grabbed from the database based on ed2k and size of the file, so the hashing is neccesary. This script is targeted at low resource NAS servers as the hashing part should be native code and it should utilize all available cores...
